# -*- coding: utf-8 -*-
"""app_graficos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KEcNN1Vnq01phV1gfH6QCpSmKoFnG3xw
"""

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import io

st.set_page_config(page_title="Gráficos de Arquitetura e Engenharia", layout="wide")

st.title("📊 Análise de Itens – Arquitetura e Engenharia")

# Upload do arquivo Excel
uploaded_file = st.file_uploader("Envie a planilha Excel (.xlsx)", type=["xlsx"])

if uploaded_file:
    df = pd.read_excel(uploaded_file, sheet_name="Planilha1")

    meses = df["Ano-Mês"].astype(str)
    x = range(len(meses))
    largura_barra = 0.35

    def gerar_grafico(colunas, titulo, cmap, posicao_barra=0, largura_barra=0.35):
        fig, ax = plt.subplots(figsize=(12, 6))
        acumulado = [0] * len(df)
        n = len(colunas)
        cores = [cmap(0.3 + (0.7) * i/(n-1)) for i in range(n)]

        for idx, coluna in enumerate(colunas):
            ax.bar(
                [pos + posicao_barra for pos in x],
                df[coluna],
                bottom=acumulado,
                width=largura_barra,
                color=cores[idx],
                label=coluna.replace("_", " ").replace("AC ", "Arquitetura - ").replace("ENG ", "Engenharia - "),
            )
            for i, val in enumerate(df[coluna]):
                if val > 0:
                    ax.text(
                        i + posicao_barra,
                        acumulado[i] + val / 2,
                        str(val),
                        ha='center', va='center', fontsize=8, color='white', fontweight='bold'
                    )
            acumulado = [acumulado[j] + df[coluna][j] for j in range(len(df))]

        ax.set_xticks(x)
        ax.set_xticklabels(meses, rotation=45)
        ax.set_ylabel("Quantidade de Itens")
        ax.set_title(titulo)
        ax.legend(ncol=2, bbox_to_anchor=(0.5, -0.15), loc="upper center")
        fig.tight_layout()
        return fig

    # --- Gerar os 3 gráficos ---
    with st.spinner("Gerando gráficos..."):
        fig_geral = plt.figure(figsize=(12, 6))
        plt.title("Itens de Arquitetura e Engenharia por Mês (Iniciada / Ongoing / Liberada)")
        plt.ylabel("Quantidade de Itens")
        plt.xticks(x, meses, rotation=45)

        def adicionar_rotulos(base_x, colunas, cmap, start=0.3, end=1.0):
            acumulado = [0] * len(df)
            n = len(colunas)
            cores = [cmap(start + (end - start) * i/(n-1)) for i in range(n)]
            for idx, coluna in enumerate(colunas):
                plt.bar(
                    base_x, df[coluna], bottom=acumulado, width=largura_barra,
                    label=coluna.replace("_", " ").replace("AC ", "Arquitetura - ").replace("ENG ", "Engenharia - "),
                    color=cores[idx]
                )
                for i, val in enumerate(df[coluna]):
                    if val > 0:
                        plt.text(base_x[i], acumulado[i] + val / 2, str(val),
                                 ha='center', va='center', fontsize=8, color='white', fontweight='bold')
                acumulado = [acumulado[j] + df[coluna][j] for j in range(len(df))]

        adicionar_rotulos([pos - largura_barra/2 for pos in x],
                          ["AC_Iniciada", "AC_Ongoing", "AC_Liberada"],
                          plt.cm.Blues)

        adicionar_rotulos([pos + largura_barra/2 for pos in x],
                          ["ENG_Iniciada", "ENG_Ongoing", "ENG_Liberada"],
                          plt.cm.Greens)

        plt.legend(ncol=2, bbox_to_anchor=(0.5, -0.15), loc="upper center")
        plt.figtext(0.5, -0.1, "Obs: Dados anteriores a outubro/2024 não estão contemplados (legado não incluso).", ha="center", fontsize=8, style="italic")
        plt.tight_layout()

        fig_arquitetura = gerar_grafico(["AC_Iniciada", "AC_Ongoing", "AC_Liberada"],
                                        "Itens de Arquitetura por Mês",
                                        plt.cm.Blues)
        fig_engenharia = gerar_grafico(["ENG_Iniciada", "ENG_Ongoing", "ENG_Liberada"],
                                       "Itens de Engenharia por Mês",
                                       plt.cm.Greens)

    # --- Mostrar os gráficos na tela ---
    st.subheader("Visão Geral")
    st.pyplot(fig_geral)

    col1, col2 = st.columns(2)
    with col1:
        st.subheader("Arquitetura")
        st.pyplot(fig_arquitetura)
    with col2:
        st.subheader("Engenharia")
        st.pyplot(fig_engenharia)

    # --- Botão de download ---
    st.subheader("📥 Baixar Gráficos")

    def fig_to_bytes(fig):
        buf = io.BytesIO()
        fig.savefig(buf, format="png", bbox_inches="tight")
        buf.seek(0)
        return buf

    st.download_button(
        label="⬇️ Baixar gráfico geral",
        data=fig_to_bytes(fig_geral),
        file_name="grafico_geral.png",
        mime="image/png"
    )

    st.download_button(
        label="⬇️ Baixar gráfico - Arquitetura",
        data=fig_to_bytes(fig_arquitetura),
        file_name="grafico_arquitetura.png",
        mime="image/png"
    )

    st.download_button(
        label="⬇️ Baixar gráfico - Engenharia",
        data=fig_to_bytes(fig_engenharia),
        file_name="grafico_engenharia.png",
        mime="image/png"
    )

else:
    st.info("👆 Envie a planilha Excel para gerar os gráficos.")